import type { Metadata } from "next";
import { Geist, Geist_Mono, Recursive } from "next/font/google";
import "./globals.css";
import Background from "@/components/models/Background";
import Navbar from "@/components/Navbar";

const recursive = Recursive({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`relative ${recursive.className}`}>
        <Navbar />
        <figure className="fixed h-[100vh] w-[100vw]">
          <Background />
        </figure>
        {children}
      </body>
    </html>
  );
}
